### ISSUE TITLE
SmartPin API docs contain info on general OmniKassa

### ISSUE THREAD

**Issue by lexvz** [wp-pay-gateways/omnikassa-2#8]
Hi there,

I am looking for documentation on the SmartPin API. There is one document where the filename suggests it is about the SmartPin API (handleiding-api-koppeling-rabo-smartpin-en_29970886.pdf), but the document is actually about the Omnikassa in general.

Is there documentation available for the SmartPin API? Specifically how to integrate from a web-app? We have a web-app to manage our cash register.

Best regards,
Lex

**Comment by rvdsteege** [comment]
This repository is the OmniKassa 2.0 payment gateway integration for the Pronamic Pay plugin for WordPress.

For support from Rabobank, please see https://www.rabobank.nl/bedrijven/betalen/klanten-laten-betalen/rabo-omnikassa-2-0/support-overzicht/rabo-smartpin-support/
